dependencies {
    modImplementation(project(":modules:CTNH-Lib")){transitive = false}
    modImplementation(project(":modules:CTPP"))

    modImplementation(ctnh.creatediesel)
    modImplementation(ctnh.curios)
    // modImplementation(ctnh.avaritia)
    modImplementation(ctnh.resourcefullib)
    modImplementation(ctnh.resourcefulconfig)

    modImplementation(ctnh.terrablender)

    modImplementation("extra-mods:worldgenrender-1.0.0:1.0.0")
}
